### ISSUE TITLE
8.4.2 initialization error

### ISSUE THREAD

**Issue by rocxteady** [sendinblue/APIv3-nodejs-library#131]
I can't start my nodejs app with the error below. The version is 8.4.2. Can you help? :(

```
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module './model/RequestSmsRecipientExport'
Require stack:
- /home/ubuntu/unimeet/node_modules/sib-api-v3-sdk/src/index.js
- /home/ubuntu/unimeet/node_modules/parse-server-sendinblue-adapter/index.js
- /home/ubuntu/unimeet/node_modules/parse-server/lib/Adapters/AdapterLoader.js
- /home/ubuntu/unimeet/node_modules/parse-server/lib/LiveQuery/ParseWebSocketServer.js
- /home/ubuntu/unimeet/node_modules/parse-server/lib/LiveQuery/ParseLiveQueryServer.js
- /home/ubuntu/unimeet/node_modules/parse-server/lib/ParseServer.js
- /home/ubuntu/unimeet/node_modules/parse-server/lib/index.js
- /home/ubuntu/unimeet/unimeet.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/ubuntu/unimeet/node_modules/sib-api-v3-sdk/src/index.js:23:4527
    at Object.<anonymous> (/home/ubuntu/unimeet/node_modules/sib-api-v3-sdk/src/index.js:25:2)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ubuntu/unimeet/node_modules/sib-api-v3-sdk/src/index.js',
    '/home/ubuntu/unimeet/node_modules/parse-server-sendinblue-adapter/index.js',
    '/home/ubuntu/unimeet/node_modules/parse-server/lib/Adapters/AdapterLoader.js',
    '/home/ubuntu/unimeet/node_modules/parse-server/lib/LiveQuery/ParseWebSocketServer.js',
    '/home/ubuntu/unimeet/node_modules/parse-server/lib/LiveQuery/ParseLiveQueryServer.js',
    '/home/ubuntu/unimeet/node_modules/parse-server/lib/ParseServer.js',
    '/home/ubuntu/unimeet/node_modules/parse-server/lib/index.js',
    '/home/ubuntu/unimeet/unimeet.js'
  ]
}
```

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @rocxteady 

I tested with this code and it worked for me:

```const SibApiV3Sdk = require('sib-api-v3-sdk');
let defaultClient = SibApiV3Sdk.ApiClient.instance;
let apiKey = defaultClient.authentications['api-key'];
apiKey.apiKey = 'YOUR_API_KEY';
var apiInstance = new SibApiV3Sdk.SMSCampaignsApi();
var campaignId = 2716; // Number | id of the campaign

var opts = { 
  'recipientExport': new SibApiV3Sdk.RequestSmsRecipientExport() // RequestSmsRecipientExport | Values to send for a recipient export request
};

opts.recipientExport.recipientsType = 'delivered'

apiInstance.requestSmsRecipientExport(campaignId, opts).then(function(data) {
  console.log('API called successfully. Returned data: ' + JSON.stringify(data));
}, function(error) {
  console.error(error);
});```


Kindly test it again and let me know if the issue persists. Btw I tested on version 8.4.2, latest one.

Happy to help!
Shubham

**Comment by shubhamUpadhyayInBlue** [comment]
Closing the issue since there is no activity for more than 11 days. Kindly open another issue if you face it again.
Thanks!
